language: rust
rust:
  - stable
  - beta
  - nightly
services:
  - postgresql
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --features=serde_derive
before_script:
  - cargo install diesel_cli
  - psql -c 'create database travis_ci_test;' -U postgres
  - pushd tests && ~/.cargo/bin/diesel migration run && popd
env:
  - DATABASE_URL=postgres://postgres@127.0.0.1/travis_ci_test
matrix:
  allow_failures:
    - rust: nightly
