language: rust
rust:
  - stable
  - beta
  - nightly
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - pushd tests && diesel migration run && popd
env:
  - DATABASE_URL=postgres://postgres@127.0.0.1/travis_ci_test
